name: Release
on:
  pull_request:
jobs:
  testimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set env
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Build JVM Docker Image
      uses: docker/build-push-action@v1
      with:
        dockerfile: 'agent/docker/jvm/Dockerfile'
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: verizondigital/kubectl-flame
        tags: ${{ steps.vars.outputs.tag }}-jvm-test
    - name: Build JVM Alpine Docker Image
      uses: docker/build-push-action@v1
      with:
        dockerfile: 'agent/docker/jvm/Dockerfile.alpine'
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: verizondigital/kubectl-flame
        tags: ${{ steps.vars.outputs.tag }}-jvm-alpine-test
    - name: Build BPF Docker Image
      uses: docker/build-push-action@v1
      with:
        dockerfile: 'agent/docker/bpf/Dockerfile'
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: verizondigital/kubectl-flame
        tags: ${{ steps.vars.outputs.tag }}-bpf